change codestyle to standard
chrishelgert/hapi-preact-views pull request #18
Opened 2017-04-04 16:03 UTC by chrishelgert

changing the codestyle to https://github.com/feross/standard

* less dependencies (in our package.json)
* less dotfiles
* fixes also #17

2017-04-04 18:15 UTC, danielbayerlein requested changes

2017-04-04 18:15 UTC, danielbayerlein commented on lib/index.js
> +// eslint-disable-next-line no-unused-vars
TODO: Why?

2017-04-05 13:35 UTC, chrishelgert commented on lib/index.js
> +// eslint-disable-next-line no-unused-vars
removed it 👍

2017-04-05 19:25 UTC, danielbayerlein approved these changes

2017-04-05 19:25 UTC, merged