add appveyor for windows-ci-build
chrishelgert/hapi-preact-views pull request #3
Opened 2017-02-11 15:05 UTC by chrishelgert

appveyor will run the ci on windows, so we can make sure, that everything is working on unix and windows.

2017-02-11 15:53 UTC, danielbayerlein requested changes

2017-02-11 15:53 UTC, danielbayerlein commented on .appveyor.yml
> +  - yarn install
Why do you install `yarn`?

2017-02-12 11:31 UTC, chrishelgert commented on .appveyor.yml
> +  - yarn install
mh? i do not install yarn, the install block will also install the dependencies i think.
i looked at the appveyor-files from fb-projects

2017-02-12 11:37 UTC, danielbayerlein approved these changes

2017-02-12 11:37 UTC, danielbayerlein approved these changes

2017-02-12 11:39 UTC, danielbayerlein commented
@chrishelgert I approved these changes. You can merge the PR, I have no authority to do this 😉

2017-02-12 12:21 UTC, chrishelgert commented
Now you have 👍🏻

2017-02-12 12:36 UTC, merged